spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:tqi-test-development
    username: application
    password:
    driver-class-name: org.h2.Driver
  flyway:
    locations: classpath:db/migration

feign:
  hystrix:
    enabled: true
